# Generated by Django 5.2 on 2026-09-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workers',
            new_name='Worker',
        ),
    ]
