# Generated by Django 5.2 on 2026-09-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_is_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('36-38', '36-38'), ('37-39', '37-39'), ('38-40', '38-40'), ('39-41', '39-41'), ('40-42', '40-42'), ('41-43', '41-43'), ('42-44', '42-44'), ('43-45', '43-45'), ('44-46', '44-46'), ('45-47', '45-47')], max_length=10, verbose_name='Размер'),
        ),
    ]
