# Generated by Django 5.2 on 2026-09-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sex',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('unisex', 'Унисекс')], max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('36-38', '36-38'), ('39-41', '39-41'), ('42-44', '42-44'), ('45-47', '45-47')], max_length=10, verbose_name='Размер'),
        ),
    ]
