# Generated by Django 5.2 on 2026-09-16 12:39

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_sex_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(help_text='Укажите диапазон размеров в наличии', max_length=10, verbose_name='Размер'),
        ),
    ]
